# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lsegura <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/03 17:55:23 by lsegura           #+#    #+#              #
#    Updated: 2024/08/04 18:21:37 by lsegura          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME = rush-02
CC = gcc
CFLAGS = -Wall -Wextra -Werror
FILES = main.c rush02.c 

all :
$(CC) $(CFLAGS) $(FILES) -o $(NAME)

clean:
	rm -f $(NAME)


